repos:
  - repo: local
    hooks:
      - id: check
        name: Check Code Issues
        entry: ruff check
        args: [ -q ]
        language: python
        files: .*\.py$
  - repo: local
    hooks:
      - id: format
        name: Format Code
        entry: ruff format
        language: python
        files: .*\.py$