settings:
  max_func_depth:
    name: max_func_depth
    help: backward slicing visits called functions up to the given depth
    value: 3
    min_value: -1
    max_value: 10
  highlight_color:
    name: highlight_color
    help: color used to highlight paths
    value: Red
    items:
    - Blue
    - Green
    - Cyan
    - Red
    - Magenta
    - Yellow
    - Orange
    - White
    - Black